### PR TITLE
Move function from midptf is added to Github

### PR DESCRIPTION
**Pull request by vgousyleblanc**
Previous important from Bitbucket contains difference from the programs that are used on the midptf computer

### CODE REVIEW

**Review by pdeperio — CHANGES_REQUESTED** [review]
Generally, could you write an overview of all the changes in the first PR post? In particular:

1. `demo_path.cxx`: what's this for? Looks like it's generated automatically somehow (how and by what program?)

2. `feMove*.cxx`: Looks like you're committing 4 versions of this program. Which one should be used by default? What are all the differences and in what case do we need to switch to each one? If these are all just revisions of a single file, normally  GitHub should be tracking these revisions (i.e. start by committing oldest version, then replace with next version and commit, and so on).

**Comment by vgousyleblanc** [comment]
So this is my understanding of the different move scripts : 
feMove.cxx (the script we are using)
feMove_prev.cxx (the script that was used before, I will dig deaper into the change that have to be made)
feMove_new.cxx (script in which the new collision avoidance was implemented just tested by simulation)
feMove_working.cxx (that I honestly don't know the difference, I will go look deeper as well)
demo_path.cxx is I think a serie of tests to be done to test the collision avoidance

**Comment by pdeperio** [comment]
OK let's assume `feMove.cxx` will be the main, current program. Please make a separate branch (and PR) for each `feMove_*` renamed to `feMove.cxx` (so we can clearly `diff` here). Then you can clearly write the description of each version in each PR, starting from `feMove_prev.cxx` and then changes moving to `feMove.cxx` and so on.

We will then merge in order the PRs, e.g.:
1. `feMove_prev.cxx` (updating from local version)
2. `feMove.cxx`
3. `feMove_new.cxx` (after testing its branch)

And wherever `feMove_working.cxx` fits in.

How does this plan sound?

**Comment by vgousyleblanc** [comment]
Yes, okay, I will try to revert the change of move and do separated pull request.

**Comment by pdeperio** [comment]
I would suggest to start from scratch with separate branches for each file renamed to `feMove.cxx`, instead of continuing on this branch/PR.

**Pull request closed without merging**
