### PR TITLE
Degauss file from the midptf computer

### PR DESCRIPTION
**Pull request by vgousyleblanc**
There was some difference between midptf and Bitbucket importation so this is made to merge the 2 versions

### CODE REVIEW

**Review by pdeperio — CHANGES_REQUESTED** [review]
I can't see any changes here. Did you miss adding the file?

**Comment by vgousyleblanc** [comment]
For a reason I don't know, the change was not reverted in the case of the degauss file. The file we have right now are the one of the midptf computer.

**Comment by pdeperio** [comment]
So I'm confused about this PR then. What exactly are you trying to update?

Also, why are the `degauss` files in the other PR https://github.com/PMT-Test-Facilities/ptf-daq-programs/pull/2?

**Comment by vgousyleblanc** [comment]
I tried to revert the files but did it in the wrong branch, but basically we can delete this pull request since as you say there is no change !

**Comment by pdeperio** [comment]
ok, you should close (since it's your PR). (Do you see the "Close" button below?)

**Pull request closed without merging**
