### PR TITLE
New midas fixes

### PR DESCRIPTION
**Pull request by thomaslindner**
The MIDAS code on midptf01 now compiles.  

Need to see why the merge isn't happy though.

### CODE REVIEW

**Comment by thomaslindner** [comment]
I will leave @vgousyleblanc and @pdeperio to look at the merge conflict for feMove.

**Comment by vgousyleblanc** [comment]
The conflict comes from the fact that we went from the untested collision avoidance to the script that was always used (I think) since you open this pull request before me and patrick did the merge yesterday. I can go fix these conflicts

**Comment by vgousyleblanc** [comment]
Here we go, so now the merge is possible, I corrected this issue of different versions !

**Review by vgousyleblanc — APPROVED** [review]
It compiles for me too on midptf !

**Comment by pdeperio** [comment]
@thomaslindner can you double check nothing was lost during the conflict resolution?

**Comment by vgousyleblanc** [comment]
Okay, I will definately go back to look at it. I think I understand what went wrong, I tought that all the conflicts came from the fact that this pull request was made before the merge, but they actually comes also from the addition that you have done. I will go correct this

**Comment by vgousyleblanc** [comment]
Okay, great, it compiled for me as well so I will merge.

**Review by vgousyleblanc — APPROVED** [review]
Great, it compiles for me as well. I apologize for being a bit too quick on my merge, I am starting how important these merge can be

**Pull request merged**
