### PR TITLE
feMove_ working upload (Move file that was also on midptf)

### PR DESCRIPTION
**Pull request by vgousyleblanc**
Doing a difference command with this move function and the feMove.cxx files gives I think a lot of adjustment that were done using the data from the phidget, configuration that were tested. Testing the previous version of the collision avoidance script as well (  goodPath01)

### CODE REVIEW

**Review by pdeperio — CHANGES_REQUESTED** [review]
As I mentioned in #5, we want `move/feMove.cxx` of the `master` branch to always be the current working program. So having other scripts with different names in the folder, especially `feMove_working.cxx`, can get confusing.

If this is just another version of `feMove.cxx`, then please rename it as such (with `git mv`), so we can directly see the diffs you briefly mention on GitHub here ("Files changed" tab above).

Are all the adjustments necessary for the "production" (`master`) version? If so, I guess you'll want to change the base branch (i.e. the target branch where the changes will be merged) to the branch in #5 (`feMove.cxx-(working-version)`) by clicking "Edit" above.

Then you'll need to make sure all the code gets merged properly, keeping all the necessary features and without breaking the currently "working" code on `midptf`.

**Comment by vgousyleblanc** [comment]
This is from what I understood another in between version of move, the final version being still the one that we use (feMove) so I suppose I will rename it and move it to the obsolete folder as well

**Review by pdeperio — APPROVED** [review]

**Comment by pdeperio** [comment]
`newest_older_version` is getting ridiculous lol there is no indication at all of what this version does. if you're ok with this file basically being lost forever and forgotten, then ok.

**Comment by vgousyleblanc** [comment]
So here is the confusion feMove_prev.cxx is the move file that was used on midptf. feMove.cxx is the collision avoidance script implemented by Mia. Which is also the reason why in the collision avoidance branch there is no new commits since the feMove file is the one that has the collision avoidance implemented ! I did some renaming of files that makes this more clear hopefully.

**Comment by pdeperio** [comment]
never mind, i should've waited for you to fix conflicts. so looks like no change to `feMove` now, but does that mean `master` now contains Mia's untested collision avoidance version?

**Review by pdeperio — APPROVED** [review]

**Pull request merged**
